<?php

namespace Database\Seeders;

use App\Models\Gift;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StrongMotionGiftsSeeder extends Seeder
{
    /**
     * Seed the 30 strong-motion animated gifts into the gifts table with top priority.
     */
    public function run(): void
    {
        // Clean out ALL old/legacy gifts completely so ONLY the 30 strong-motion gifts exist
        try {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
            DB::table('gifts')->truncate();
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        } catch (\Throwable $e) {
            DB::table('gifts')->delete();
        }

        $gifts = [
            [
                'name'                => 'Red Rose',
                'slug'                => 'rose',
                'coins'               => 10,
                'coin_price'          => 10,
                'category'            => 'hot',
                'badge'               => 'ROSE',
                'image'               => 'uploads/gifts/01_rose.svg',
                'icon_url'            => 'uploads/gifts/01_rose.svg',
                'animation_url'       => 'uploads/gifts/01_rose.svg',
                'animation_asset_url' => 'uploads/gifts/01_rose.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 1,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Classic romantic red rose with blooming petals motion',
            ],
            [
                'name'                => 'Diamond Heart',
                'slug'                => 'diamond_heart',
                'coins'               => 520,
                'coin_price'          => 520,
                'category'            => 'romantic',
                'badge'               => '520 LOVE',
                'image'               => 'uploads/gifts/02_diamond_heart.svg',
                'icon_url'            => 'uploads/gifts/02_diamond_heart.svg',
                'animation_url'       => 'uploads/gifts/02_diamond_heart.svg',
                'animation_asset_url' => 'uploads/gifts/02_diamond_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 2,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Sparkling diamond gemstone heart with radiant light beams',
            ],
            [
                'name'                => 'Blue Diamond',
                'slug'                => 'blue_diamond',
                'coins'               => 1000,
                'coin_price'          => 1000,
                'category'            => 'wealth',
                'badge'               => 'DIAMOND',
                'image'               => 'uploads/gifts/03_blue_diamond.svg',
                'icon_url'            => 'uploads/gifts/03_blue_diamond.svg',
                'animation_url'       => 'uploads/gifts/03_blue_diamond.svg',
                'animation_asset_url' => 'uploads/gifts/03_blue_diamond.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 3,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Brilliant crystal blue diamond radiating with sparkling facets',
            ],
            [
                'name'                => 'Teddy Bear',
                'slug'                => 'teddy_bear',
                'coins'               => 299,
                'coin_price'          => 299,
                'category'            => 'cute',
                'badge'               => 'CUTE',
                'image'               => 'uploads/gifts/04_teddy_bear.svg',
                'icon_url'            => 'uploads/gifts/04_teddy_bear.svg',
                'animation_url'       => 'uploads/gifts/04_teddy_bear.svg',
                'animation_asset_url' => 'uploads/gifts/04_teddy_bear.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 4,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Fluffy cuddly teddy bear holding sweet love heart',
            ],
            [
                'name'                => 'Imperial Crown',
                'slug'                => 'crown',
                'coins'               => 3000,
                'coin_price'          => 3000,
                'category'            => 'luxury',
                'badge'               => 'CROWN',
                'image'               => 'uploads/gifts/05_crown.svg',
                'icon_url'            => 'uploads/gifts/05_crown.svg',
                'animation_url'       => 'uploads/gifts/05_crown.svg',
                'animation_asset_url' => 'uploads/gifts/05_crown.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 5,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Pure 24K gold imperial crown with embedded ruby gems',
            ],
            [
                'name'                => 'Surprise Gift Box',
                'slug'                => 'gift_box',
                'coins'               => 199,
                'coin_price'          => 199,
                'category'            => 'lucky',
                'badge'               => 'SURPRISE',
                'image'               => 'uploads/gifts/06_gift_box.svg',
                'icon_url'            => 'uploads/gifts/06_gift_box.svg',
                'animation_url'       => 'uploads/gifts/06_gift_box.svg',
                'animation_asset_url' => 'uploads/gifts/06_gift_box.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 6,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Shining golden tied present box opening with magical sparks',
            ],
            [
                'name'                => 'Flower Bouquet',
                'slug'                => 'flower_bouquet',
                'coins'               => 666,
                'coin_price'          => 666,
                'category'            => 'romantic',
                'badge'               => 'ROMANCE',
                'image'               => 'uploads/gifts/07_flower_bouquet.svg',
                'icon_url'            => 'uploads/gifts/07_flower_bouquet.svg',
                'animation_url'       => 'uploads/gifts/07_flower_bouquet.svg',
                'animation_asset_url' => 'uploads/gifts/07_flower_bouquet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 7,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Fresh blooming flower bouquet with pink tulips and carnations',
            ],
            [
                'name'                => 'Gold Coins Shower',
                'slug'                => 'gold_coins',
                'coins'               => 888,
                'coin_price'          => 888,
                'category'            => 'wealth',
                'badge'               => 'RICH',
                'image'               => 'uploads/gifts/08_gold_coins.svg',
                'icon_url'            => 'uploads/gifts/08_gold_coins.svg',
                'animation_url'       => 'uploads/gifts/08_gold_coins.svg',
                'animation_asset_url' => 'uploads/gifts/08_gold_coins.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 8,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Raining gold dollar coins and shimmering bullion bars',
            ],
            [
                'name'                => 'Super Sports Car',
                'slug'                => 'sports_car',
                'coins'               => 5000,
                'coin_price'          => 5000,
                'category'            => 'luxury',
                'badge'               => 'SUPERCAR',
                'image'               => 'uploads/gifts/09_sports_car.svg',
                'icon_url'            => 'uploads/gifts/09_sports_car.svg',
                'animation_url'       => 'uploads/gifts/09_sports_car.svg',
                'animation_asset_url' => 'uploads/gifts/09_sports_car.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 9,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Ultra luxury speed supercar zooming across the live room',
            ],
            [
                'name'                => 'Private Jet Airplane',
                'slug'                => 'airplane',
                'coins'               => 10000,
                'coin_price'          => 10000,
                'category'            => 'luxury',
                'badge'               => 'JET',
                'image'               => 'uploads/gifts/10_airplane.svg',
                'icon_url'            => 'uploads/gifts/10_airplane.svg',
                'animation_url'       => 'uploads/gifts/10_airplane.svg',
                'animation_asset_url' => 'uploads/gifts/10_airplane.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 10,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Sleek executive private jet soaring through golden clouds',
            ],
            [
                'name'                => 'Birthday Cake',
                'slug'                => 'birthday_cake',
                'coins'               => 1314,
                'coin_price'          => 1314,
                'category'            => 'party',
                'badge'               => 'BDAY',
                'image'               => 'uploads/gifts/11_birthday_cake.svg',
                'icon_url'            => 'uploads/gifts/11_birthday_cake.svg',
                'animation_url'       => 'uploads/gifts/11_birthday_cake.svg',
                'animation_asset_url' => 'uploads/gifts/11_birthday_cake.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 11,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Celebration birthday cream cake glowing with lit candles',
            ],
            [
                'name'                => 'Glowing Butterfly',
                'slug'                => 'butterfly',
                'coins'               => 450,
                'coin_price'          => 450,
                'category'            => 'romantic',
                'badge'               => 'MAGIC',
                'image'               => 'uploads/gifts/12_butterfly.svg',
                'icon_url'            => 'uploads/gifts/12_butterfly.svg',
                'animation_url'       => 'uploads/gifts/12_butterfly.svg',
                'animation_asset_url' => 'uploads/gifts/12_butterfly.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 12,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Luminescent neon butterfly fluttering with trail sparkles',
            ],
            [
                'name'                => 'Luxury Champagne',
                'slug'                => 'champagne',
                'coins'               => 777,
                'coin_price'          => 777,
                'category'            => 'party',
                'badge'               => 'CHEERS',
                'image'               => 'uploads/gifts/13_champagne.svg',
                'icon_url'            => 'uploads/gifts/13_champagne.svg',
                'animation_url'       => 'uploads/gifts/13_champagne.svg',
                'animation_asset_url' => 'uploads/gifts/13_champagne.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 13,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Popping vintage champagne bottle splashing golden bubbles',
            ],
            [
                'name'                => 'Ocean Dolphin',
                'slug'                => 'dolphin',
                'coins'               => 2500,
                'coin_price'          => 2500,
                'category'            => 'cute',
                'badge'               => 'DOLPHIN',
                'image'               => 'uploads/gifts/14_dolphin.svg',
                'icon_url'            => 'uploads/gifts/14_dolphin.svg',
                'animation_url'       => 'uploads/gifts/14_dolphin.svg',
                'animation_asset_url' => 'uploads/gifts/14_dolphin.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 14,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Playful ocean dolphin leaping out of crystal azure water',
            ],
            [
                'name'                => 'Magic Wishing Star',
                'slug'                => 'magic_star',
                'coins'               => 520,
                'coin_price'          => 520,
                'category'            => 'lucky',
                'badge'               => 'WISH',
                'image'               => 'uploads/gifts/15_magic_star.svg',
                'icon_url'            => 'uploads/gifts/15_magic_star.svg',
                'animation_url'       => 'uploads/gifts/15_magic_star.svg',
                'animation_asset_url' => 'uploads/gifts/15_magic_star.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 15,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Enchanted wishing star sparkling with magical stardust trail',
            ],
            [
                'name'                => 'Cute Panda Delight',
                'slug'                => 'panda',
                'coins'               => 199,
                'coin_price'          => 199,
                'category'            => 'cute',
                'badge'               => 'PANDA',
                'image'               => 'uploads/gifts/16_panda.svg',
                'icon_url'            => 'uploads/gifts/16_panda.svg',
                'animation_url'       => 'uploads/gifts/16_panda.svg',
                'animation_asset_url' => 'uploads/gifts/16_panda.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 16,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Adorable cuddly panda chewing fresh bamboo shoot',
            ],
            [
                'name'                => 'Korean Finger Heart',
                'slug'                => 'finger_heart',
                'coins'               => 66,
                'coin_price'          => 66,
                'category'            => 'romantic',
                'badge'               => 'SARANGHAE',
                'image'               => 'uploads/gifts/17_finger_heart.svg',
                'icon_url'            => 'uploads/gifts/17_finger_heart.svg',
                'animation_url'       => 'uploads/gifts/17_finger_heart.svg',
                'animation_asset_url' => 'uploads/gifts/17_finger_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 17,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Trendy K-pop finger heart gesture bursting with pink neon energy',
            ],
            [
                'name'                => 'Sacred Angel Heart',
                'slug'                => 'angel_heart',
                'coins'               => 3333,
                'coin_price'          => 3333,
                'category'            => 'romantic',
                'badge'               => 'SACRED',
                'image'               => 'uploads/gifts/18_angel_heart.svg',
                'icon_url'            => 'uploads/gifts/18_angel_heart.svg',
                'animation_url'       => 'uploads/gifts/18_angel_heart.svg',
                'animation_asset_url' => 'uploads/gifts/18_angel_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 18,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Ruby heart flanked with glowing golden feathers and halo',
            ],
            [
                'name'                => '1000 Rose Bouquet',
                'slug'                => 'rose_bouquet',
                'coins'               => 999,
                'coin_price'          => 999,
                'category'            => 'romantic',
                'badge'               => '999 ROSES',
                'image'               => 'uploads/gifts/19_rose_bouquet.svg',
                'icon_url'            => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_url'       => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_asset_url' => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 19,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Giant luxury red velvet rose bouquet wrapped in gold ribbon',
            ],
            [
                'name'                => 'Super Luxury Yacht 3D',
                'slug'                => 'luxury_yacht',
                'coins'               => 18888,
                'coin_price'          => 18888,
                'category'            => 'svip',
                'badge'               => 'SUPER YACHT',
                'image'               => 'uploads/gifts/20_luxury_yacht.svg',
                'icon_url'            => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_url'       => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_asset_url' => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 20,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Twin-deck super yacht cruise gliding across twilight waters',
            ],
            [
                'name'                => 'Diamond Rain Shower',
                'slug'                => 'diamond_shower',
                'coins'               => 7777,
                'coin_price'          => 7777,
                'category'            => 'wealth',
                'badge'               => 'DIAMOND RAIN',
                'image'               => 'uploads/gifts/21_diamond_shower.svg',
                'icon_url'            => 'uploads/gifts/21_diamond_shower.svg',
                'animation_url'       => 'uploads/gifts/21_diamond_shower.svg',
                'animation_asset_url' => 'uploads/gifts/21_diamond_shower.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 21,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Cascading shower of brilliant sparkling blue and white diamonds',
            ],
            [
                'name'                => 'Emperor Royal Crown',
                'slug'                => 'royal_crown',
                'coins'               => 8888,
                'coin_price'          => 8888,
                'category'            => 'luxury',
                'badge'               => 'EMPEROR',
                'image'               => 'uploads/gifts/22_royal_crown.svg',
                'icon_url'            => 'uploads/gifts/22_royal_crown.svg',
                'animation_url'       => 'uploads/gifts/22_royal_crown.svg',
                'animation_asset_url' => 'uploads/gifts/22_royal_crown.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 22,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Supreme monarchy emperor crown studded with precious gems',
            ],
            [
                'name'                => 'Supernova Space Rocket',
                'slug'                => 'rocket',
                'coins'               => 12000,
                'coin_price'          => 12000,
                'category'            => 'svip',
                'badge'               => 'SUPERNOVA',
                'image'               => 'uploads/gifts/23_rocket.svg',
                'icon_url'            => 'uploads/gifts/23_rocket.svg',
                'animation_url'       => 'uploads/gifts/23_rocket.svg',
                'animation_asset_url' => 'uploads/gifts/23_rocket.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 23,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Interstellar rocket blazing with plasma boost trail',
            ],
            [
                'name'                => 'Deep Space Galaxy',
                'slug'                => 'galaxy',
                'coins'               => 35000,
                'coin_price'          => 35000,
                'category'            => 'svip',
                'badge'               => 'UNIVERSE',
                'image'               => 'uploads/gifts/24_galaxy.svg',
                'icon_url'            => 'uploads/gifts/24_galaxy.svg',
                'animation_url'       => 'uploads/gifts/24_galaxy.svg',
                'animation_asset_url' => 'uploads/gifts/24_galaxy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 24,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Epic spinning cosmic vortex with orbital planetary rings',
            ],
            [
                'name'                => 'Mystic Crescent Moon',
                'slug'                => 'moon',
                'coins'               => 4500,
                'coin_price'          => 4500,
                'category'            => 'romantic',
                'badge'               => 'MOONLIGHT',
                'image'               => 'uploads/gifts/25_moon.svg',
                'icon_url'            => 'uploads/gifts/25_moon.svg',
                'animation_url'       => 'uploads/gifts/25_moon.svg',
                'animation_asset_url' => 'uploads/gifts/25_moon.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 25,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Dreamy silver crescent moon glowing with stardust clouds',
            ],
            [
                'name'                => 'Radiant Golden Sun',
                'slug'                => 'golden_sun',
                'coins'               => 9999,
                'coin_price'          => 9999,
                'category'            => 'wealth',
                'badge'               => 'SOLAR',
                'image'               => 'uploads/gifts/26_golden_sun.svg',
                'icon_url'            => 'uploads/gifts/26_golden_sun.svg',
                'animation_url'       => 'uploads/gifts/26_golden_sun.svg',
                'animation_asset_url' => 'uploads/gifts/26_golden_sun.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 26,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Golden solar flare aura emanating majestic warmth and power',
            ],
            [
                'name'                => 'Ringed Celestial Planet',
                'slug'                => 'planet',
                'coins'               => 16000,
                'coin_price'          => 16000,
                'category'            => 'svip',
                'badge'               => 'SATURN',
                'image'               => 'uploads/gifts/27_planet.svg',
                'icon_url'            => 'uploads/gifts/27_planet.svg',
                'animation_url'       => 'uploads/gifts/27_planet.svg',
                'animation_asset_url' => 'uploads/gifts/27_planet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 27,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Saturn-like giant celestial body surrounded by spinning rings',
            ],
            [
                'name'                => 'World Champion Cup 2026',
                'slug'                => 'champion_trophy',
                'coins'               => 2026,
                'coin_price'          => 2026,
                'category'            => 'party',
                'badge'               => '2026 CUP',
                'image'               => 'uploads/gifts/28_champion_trophy.svg',
                'icon_url'            => 'uploads/gifts/28_champion_trophy.svg',
                'animation_url'       => 'uploads/gifts/28_champion_trophy.svg',
                'animation_asset_url' => 'uploads/gifts/28_champion_trophy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 28,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Shining golden trophy cup for the ultimate stream champion',
            ],
            [
                'name'                => 'Diamond Fortress Castle',
                'slug'                => 'diamond_castle',
                'coins'               => 40000,
                'coin_price'          => 40000,
                'category'            => 'svip',
                'badge'               => '40K CASTLE',
                'image'               => 'uploads/gifts/29_diamond_castle.svg',
                'icon_url'            => 'uploads/gifts/29_diamond_castle.svg',
                'animation_url'       => 'uploads/gifts/29_diamond_castle.svg',
                'animation_asset_url' => 'uploads/gifts/29_diamond_castle.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 29,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Fairy tale crystal diamond fortress with shimmering towers',
            ],
            [
                'name'                => 'Imperial Royal Palace',
                'slug'                => 'royal_palace',
                'coins'               => 50000,
                'coin_price'          => 50000,
                'category'            => 'svip',
                'badge'               => '50K PALACE',
                'image'               => 'uploads/gifts/30_royal_palace.svg',
                'icon_url'            => 'uploads/gifts/30_royal_palace.svg',
                'animation_url'       => 'uploads/gifts/30_royal_palace.svg',
                'animation_asset_url' => 'uploads/gifts/30_royal_palace.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 30,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Grand imperial royal palace with fireworks and gold gates',
            ],
        ];

        foreach ($gifts as $giftData) {
            Gift::create($giftData);
        }
    }
}
