<?php

namespace Database\Seeders;

use App\Models\Gift;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class StrongMotionGiftsSeeder extends Seeder
{
    /**
     * Seed the 30 strong-motion animated gifts into the gifts table with top priority.
     */
    public function run(): void
    {
        // 1. Shift existing gifts so our 30 strong-motion animated gifts take sort_order 1 to 30
        DB::table('gifts')->where('sort_order', '<', 50)->update([
            'sort_order' => DB::raw('sort_order + 30')
        ]);

        $gifts = [
            [
                'name'                => 'Red Rose',
                'slug'                => 'rose',
                'coins'               => 10,
                'coin_price'          => 10,
                'category'            => 'hot',
                'badge'               => 'ROSE',
                'image'               => 'uploads/gifts/01_rose.svg',
                'icon_url'            => 'uploads/gifts/01_rose.svg',
                'animation_url'       => 'uploads/gifts/01_rose.svg',
                'animation_asset_url' => 'uploads/gifts/01_rose.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 1,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Classic romantic red rose with blooming petals motion',
            ],
            [
                'name'                => 'Diamond Heart',
                'slug'                => 'diamond_heart',
                'coins'               => 520,
                'coin_price'          => 520,
                'category'            => 'romantic',
                'badge'               => '520 LOVE',
                'image'               => 'uploads/gifts/02_diamond_heart.svg',
                'icon_url'            => 'uploads/gifts/02_diamond_heart.svg',
                'animation_url'       => 'uploads/gifts/02_diamond_heart.svg',
                'animation_asset_url' => 'uploads/gifts/02_diamond_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 2,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Sparkling diamond gemstone heart with radiant light beams',
            ],
            [
                'name'                => 'Blue Diamond',
                'slug'                => 'blue_diamond',
                'coins'               => 1000,
                'coin_price'          => 1000,
                'category'            => 'wealth',
                'badge'               => 'DIAMOND',
                'image'               => 'uploads/gifts/03_blue_diamond.svg',
                'icon_url'            => 'uploads/gifts/03_blue_diamond.svg',
                'animation_url'       => 'uploads/gifts/03_blue_diamond.svg',
                'animation_asset_url' => 'uploads/gifts/03_blue_diamond.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 3,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Rare glowing blue sapphire diamond with shimmer effect',
            ],
            [
                'name'                => 'Teddy Bear',
                'slug'                => 'teddy_bear',
                'coins'               => 299,
                'coin_price'          => 299,
                'category'            => 'popular',
                'badge'               => 'CUTE',
                'image'               => 'uploads/gifts/04_teddy_bear.svg',
                'icon_url'            => 'uploads/gifts/04_teddy_bear.svg',
                'animation_url'       => 'uploads/gifts/04_teddy_bear.svg',
                'animation_asset_url' => 'uploads/gifts/04_teddy_bear.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 4,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Cute cuddly teddy bear holding heart',
            ],
            [
                'name'                => 'Imperial Crown',
                'slug'                => 'imperial_crown',
                'coins'               => 3000,
                'coin_price'          => 3000,
                'category'            => 'vip',
                'badge'               => 'CROWN',
                'image'               => 'uploads/gifts/05_crown.svg',
                'icon_url'            => 'uploads/gifts/05_crown.svg',
                'animation_url'       => 'uploads/gifts/05_crown.svg',
                'animation_asset_url' => 'uploads/gifts/05_crown.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 5,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Majestic golden imperial royal crown with gems',
            ],
            [
                'name'                => 'Surprise Gift Box',
                'slug'                => 'surprise_gift_box',
                'coins'               => 199,
                'coin_price'          => 199,
                'category'            => 'hot',
                'badge'               => 'SURPRISE',
                'image'               => 'uploads/gifts/06_gift_box.svg',
                'icon_url'            => 'uploads/gifts/06_gift_box.svg',
                'animation_url'       => 'uploads/gifts/06_gift_box.svg',
                'animation_asset_url' => 'uploads/gifts/06_gift_box.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 6,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Mystery celebration gift box with bursting confetti',
            ],
            [
                'name'                => 'Flower Bouquet',
                'slug'                => 'flower_bouquet',
                'coins'               => 666,
                'coin_price'          => 666,
                'category'            => 'romantic',
                'badge'               => 'ROMANCE',
                'image'               => 'uploads/gifts/07_flower_bouquet.svg',
                'icon_url'            => 'uploads/gifts/07_flower_bouquet.svg',
                'animation_url'       => 'uploads/gifts/07_flower_bouquet.svg',
                'animation_asset_url' => 'uploads/gifts/07_flower_bouquet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 7,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Fresh multi-colored flower bouquet arrangement',
            ],
            [
                'name'                => 'Gold Coins Shower',
                'slug'                => 'gold_coins_shower',
                'coins'               => 888,
                'coin_price'          => 888,
                'category'            => 'wealth',
                'badge'               => 'RICH',
                'image'               => 'uploads/gifts/08_gold_coins.svg',
                'icon_url'            => 'uploads/gifts/08_gold_coins.svg',
                'animation_url'       => 'uploads/gifts/08_gold_coins.svg',
                'animation_asset_url' => 'uploads/gifts/08_gold_coins.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 8,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Shower of shining gold coins and jackpot wealth',
            ],
            [
                'name'                => 'Super Sports Car',
                'slug'                => 'super_sports_car',
                'coins'               => 5000,
                'coin_price'          => 5000,
                'category'            => 'luxury',
                'badge'               => 'SUPERCAR',
                'image'               => 'uploads/gifts/09_sports_car.svg',
                'icon_url'            => 'uploads/gifts/09_sports_car.svg',
                'animation_url'       => 'uploads/gifts/09_sports_car.svg',
                'animation_asset_url' => 'uploads/gifts/09_sports_car.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 9,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Luxury aerodynamic supercar speed drive-by animation',
            ],
            [
                'name'                => 'Private Jet Airplane',
                'slug'                => 'private_jet_airplane',
                'coins'               => 10000,
                'coin_price'          => 10000,
                'category'            => 'luxury',
                'badge'               => 'JET',
                'image'               => 'uploads/gifts/10_airplane.svg',
                'icon_url'            => 'uploads/gifts/10_airplane.svg',
                'animation_url'       => 'uploads/gifts/10_airplane.svg',
                'animation_asset_url' => 'uploads/gifts/10_airplane.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 10,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Billionaire private jet airliner soaring through the sky',
            ],
            [
                'name'                => 'Birthday Cake',
                'slug'                => 'birthday_cake',
                'coins'               => 1314,
                'coin_price'          => 1314,
                'category'            => 'festival',
                'badge'               => 'BDAY',
                'image'               => 'uploads/gifts/11_birthday_cake.svg',
                'icon_url'            => 'uploads/gifts/11_birthday_cake.svg',
                'animation_url'       => 'uploads/gifts/11_birthday_cake.svg',
                'animation_asset_url' => 'uploads/gifts/11_birthday_cake.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 11,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Tiered birthday celebration cake with glowing candles',
            ],
            [
                'name'                => 'Glowing Butterfly',
                'slug'                => 'glowing_butterfly',
                'coins'               => 450,
                'coin_price'          => 450,
                'category'            => 'effects',
                'badge'               => 'MAGIC',
                'image'               => 'uploads/gifts/12_butterfly.svg',
                'icon_url'            => 'uploads/gifts/12_butterfly.svg',
                'animation_url'       => 'uploads/gifts/12_butterfly.svg',
                'animation_asset_url' => 'uploads/gifts/12_butterfly.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 12,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Enchanted neon glowing butterfly flutter animation',
            ],
            [
                'name'                => 'Champagne Celebration',
                'slug'                => 'champagne_celebration',
                'coins'               => 999,
                'coin_price'          => 999,
                'category'            => 'hot',
                'badge'               => 'PARTY',
                'image'               => 'uploads/gifts/13_champagne.svg',
                'icon_url'            => 'uploads/gifts/13_champagne.svg',
                'animation_url'       => 'uploads/gifts/13_champagne.svg',
                'animation_asset_url' => 'uploads/gifts/13_champagne.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 13,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Popping champagne bottle and bubbling luxury glasses',
            ],
            [
                'name'                => 'Ocean Dolphin',
                'slug'                => 'ocean_dolphin',
                'coins'               => 2500,
                'coin_price'          => 2500,
                'category'            => 'popular',
                'badge'               => 'OCEAN',
                'image'               => 'uploads/gifts/14_dolphin.svg',
                'icon_url'            => 'uploads/gifts/14_dolphin.svg',
                'animation_url'       => 'uploads/gifts/14_dolphin.svg',
                'animation_asset_url' => 'uploads/gifts/14_dolphin.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 14,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Playful ocean dolphin jumping over dynamic water waves',
            ],
            [
                'name'                => 'Magic Wishing Star',
                'slug'                => 'magic_wishing_star',
                'coins'               => 777,
                'coin_price'          => 777,
                'category'            => 'lucky',
                'badge'               => 'WISH',
                'image'               => 'uploads/gifts/15_magic_star.svg',
                'icon_url'            => 'uploads/gifts/15_magic_star.svg',
                'animation_url'       => 'uploads/gifts/15_magic_star.svg',
                'animation_asset_url' => 'uploads/gifts/15_magic_star.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 15,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Twinkling gold wishing star with stardust trail',
            ],
            [
                'name'                => 'Cute Panda',
                'slug'                => 'cute_panda',
                'coins'               => 350,
                'coin_price'          => 350,
                'category'            => 'popular',
                'badge'               => 'PANDA',
                'image'               => 'uploads/gifts/16_panda.svg',
                'icon_url'            => 'uploads/gifts/16_panda.svg',
                'animation_url'       => 'uploads/gifts/16_panda.svg',
                'animation_asset_url' => 'uploads/gifts/16_panda.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 16,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Adorable cuddly panda bear with playful animation',
            ],
            [
                'name'                => 'Finger Heart',
                'slug'                => 'finger_heart',
                'coins'               => 99,
                'coin_price'          => 99,
                'category'            => 'hot',
                'badge'               => 'SARANG',
                'image'               => 'uploads/gifts/17_finger_heart.svg',
                'icon_url'            => 'uploads/gifts/17_finger_heart.svg',
                'animation_url'       => 'uploads/gifts/17_finger_heart.svg',
                'animation_asset_url' => 'uploads/gifts/17_finger_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 17,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'K-Pop Korean finger heart love gesture',
            ],
            [
                'name'                => 'Angel Wings Heart',
                'slug'                => 'angel_wings_heart',
                'coins'               => 1500,
                'coin_price'          => 1500,
                'category'            => 'romantic',
                'badge'               => 'ANGEL',
                'image'               => 'uploads/gifts/18_angel_heart.svg',
                'icon_url'            => 'uploads/gifts/18_angel_heart.svg',
                'animation_url'       => 'uploads/gifts/18_angel_heart.svg',
                'animation_asset_url' => 'uploads/gifts/18_angel_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 18,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Golden angelic wings hugging a radiant love heart',
            ],
            [
                'name'                => '999 Roses Bouquet',
                'slug'                => '999_roses_bouquet',
                'coins'               => 9999,
                'coin_price'          => 9999,
                'category'            => 'romantic',
                'badge'               => '999 ROSES',
                'image'               => 'uploads/gifts/19_rose_bouquet.svg',
                'icon_url'            => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_url'       => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_asset_url' => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 19,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Grand deluxe 999 red roses bouquet of infinite love',
            ],
            [
                'name'                => 'Luxury Super Yacht',
                'slug'                => 'luxury_super_yacht',
                'coins'               => 15000,
                'coin_price'          => 15000,
                'category'            => 'luxury',
                'badge'               => 'YACHT',
                'image'               => 'uploads/gifts/20_luxury_yacht.svg',
                'icon_url'            => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_url'       => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_asset_url' => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 20,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Billionaire super yacht sailing on turquoise water',
            ],
            [
                'name'                => 'Diamond Shower Storm',
                'slug'                => 'diamond_shower_storm',
                'coins'               => 20000,
                'coin_price'          => 20000,
                'category'            => 'wealth',
                'badge'               => 'DIAMOND',
                'image'               => 'uploads/gifts/21_diamond_shower.svg',
                'icon_url'            => 'uploads/gifts/21_diamond_shower.svg',
                'animation_url'       => 'uploads/gifts/21_diamond_shower.svg',
                'animation_asset_url' => 'uploads/gifts/21_diamond_shower.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 21,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Full-screen storm of cascading glittering diamonds',
            ],
            [
                'name'                => 'Sovereign Royal Crown',
                'slug'                => 'sovereign_royal_crown',
                'coins'               => 25000,
                'coin_price'          => 25000,
                'category'            => 'svip',
                'badge'               => 'SVIP',
                'image'               => 'uploads/gifts/22_royal_crown.svg',
                'icon_url'            => 'uploads/gifts/22_royal_crown.svg',
                'animation_url'       => 'uploads/gifts/22_royal_crown.svg',
                'animation_asset_url' => 'uploads/gifts/22_royal_crown.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 22,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Imperial sovereign gold and velvet monarch crown',
            ],
            [
                'name'                => 'Space Rocket Launch',
                'slug'                => 'space_rocket_launch',
                'coins'               => 30000,
                'coin_price'          => 30000,
                'category'            => 'effects',
                'badge'               => 'ROCKET',
                'image'               => 'uploads/gifts/23_rocket.svg',
                'icon_url'            => 'uploads/gifts/23_rocket.svg',
                'animation_url'       => 'uploads/gifts/23_rocket.svg',
                'animation_asset_url' => 'uploads/gifts/23_rocket.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 23,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Epic space rocket blastoff with flame and smoke animation',
            ],
            [
                'name'                => 'Nebula Galaxy Universe',
                'slug'                => 'nebula_galaxy_universe',
                'coins'               => 35000,
                'coin_price'          => 35000,
                'category'            => 'effects',
                'badge'               => 'GALAXY',
                'image'               => 'uploads/gifts/24_galaxy.svg',
                'icon_url'            => 'uploads/gifts/24_galaxy.svg',
                'animation_url'       => 'uploads/gifts/24_galaxy.svg',
                'animation_asset_url' => 'uploads/gifts/24_galaxy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 24,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Spinning cosmic spiral galaxy with starlight dust',
            ],
            [
                'name'                => 'Romantic Crescent Moon',
                'slug'                => 'romantic_crescent_moon',
                'coins'               => 12000,
                'coin_price'          => 12000,
                'category'            => 'romantic',
                'badge'               => 'MOON',
                'image'               => 'uploads/gifts/25_moon.svg',
                'icon_url'            => 'uploads/gifts/25_moon.svg',
                'animation_url'       => 'uploads/gifts/25_moon.svg',
                'animation_asset_url' => 'uploads/gifts/25_moon.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 25,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Golden crescent moon nestled in starry night sky',
            ],
            [
                'name'                => 'Radiant Golden Sun',
                'slug'                => 'radiant_golden_sun',
                'coins'               => 18000,
                'coin_price'          => 18000,
                'category'            => 'wealth',
                'badge'               => 'SUN',
                'image'               => 'uploads/gifts/26_golden_sun.svg',
                'icon_url'            => 'uploads/gifts/26_golden_sun.svg',
                'animation_url'       => 'uploads/gifts/26_golden_sun.svg',
                'animation_asset_url' => 'uploads/gifts/26_golden_sun.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 26,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Blazing solar golden sun with revolving corona rays',
            ],
            [
                'name'                => 'Cosmic Ring Planet',
                'slug'                => 'cosmic_ring_planet',
                'coins'               => 22000,
                'coin_price'          => 22000,
                'category'            => 'effects',
                'badge'               => 'PLANET',
                'image'               => 'uploads/gifts/27_planet.svg',
                'icon_url'            => 'uploads/gifts/27_planet.svg',
                'animation_url'       => 'uploads/gifts/27_planet.svg',
                'animation_asset_url' => 'uploads/gifts/27_planet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 27,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Majestic celestial planet with glowing orbital rings',
            ],
            [
                'name'                => 'Champion Gold Trophy',
                'slug'                => 'champion_gold_trophy',
                'coins'               => 8000,
                'coin_price'          => 8000,
                'category'            => 'hot',
                'badge'               => 'CHAMPION',
                'image'               => 'uploads/gifts/28_champion_trophy.svg',
                'icon_url'            => 'uploads/gifts/28_champion_trophy.svg',
                'animation_url'       => 'uploads/gifts/28_champion_trophy.svg',
                'animation_asset_url' => 'uploads/gifts/28_champion_trophy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 28,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Grand winner championship gold cup with victory star',
            ],
            [
                'name'                => 'Crystal Diamond Castle',
                'slug'                => 'crystal_diamond_castle',
                'coins'               => 40000,
                'coin_price'          => 40000,
                'category'            => 'svip',
                'badge'               => 'CASTLE',
                'image'               => 'uploads/gifts/29_diamond_castle.svg',
                'icon_url'            => 'uploads/gifts/29_diamond_castle.svg',
                'animation_url'       => 'uploads/gifts/29_diamond_castle.svg',
                'animation_asset_url' => 'uploads/gifts/29_diamond_castle.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 29,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Fairy tale crystal diamond fortress with shimmering towers',
            ],
            [
                'name'                => 'Imperial Royal Palace',
                'slug'                => 'imperial_royal_palace',
                'coins'               => 50000,
                'coin_price'          => 50000,
                'category'            => 'svip',
                'badge'               => '50K PALACE',
                'image'               => 'uploads/gifts/30_royal_palace.svg',
                'icon_url'            => 'uploads/gifts/30_royal_palace.svg',
                'animation_url'       => 'uploads/gifts/30_royal_palace.svg',
                'animation_asset_url' => 'uploads/gifts/30_royal_palace.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 30,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Grand imperial royal palace with fireworks and gold gates',
            ],
        ];

        foreach ($gifts as $giftData) {
            Gift::updateOrCreate(
                ['slug' => $giftData['slug']],
                $giftData
            );
        }
    }
}
