<?php

use App\Models\CoinPackage;
use App\Models\Gift;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Clean out ALL old/legacy gifts completely so ONLY the 30 strong-motion gifts exist
        try {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
            DB::table('gifts')->truncate();
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        } catch (\Throwable $e) {
            DB::table('gifts')->delete();
        }

        $gifts = [
            [
                'name'                => 'Red Rose',
                'slug'                => 'rose',
                'coins'               => 10,
                'coin_price'          => 10,
                'category'            => 'hot',
                'badge'               => 'ROSE',
                'image'               => 'uploads/gifts/01_rose.svg',
                'icon_url'            => 'uploads/gifts/01_rose.svg',
                'animation_url'       => 'uploads/gifts/01_rose.svg',
                'animation_asset_url' => 'uploads/gifts/01_rose.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 1,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Classic romantic red rose with blooming petals motion',
            ],
            [
                'name'                => 'Diamond Heart',
                'slug'                => 'diamond_heart',
                'coins'               => 520,
                'coin_price'          => 520,
                'category'            => 'romantic',
                'badge'               => '520 LOVE',
                'image'               => 'uploads/gifts/02_diamond_heart.svg',
                'icon_url'            => 'uploads/gifts/02_diamond_heart.svg',
                'animation_url'       => 'uploads/gifts/02_diamond_heart.svg',
                'animation_asset_url' => 'uploads/gifts/02_diamond_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 2,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Sparkling diamond gemstone heart with radiant light beams',
            ],
            [
                'name'                => 'Super Car',
                'slug'                => 'super_car',
                'coins'               => 5000,
                'coin_price'          => 5000,
                'category'            => 'luxury',
                'badge'               => 'SUPERCAR',
                'image'               => 'uploads/gifts/03_super_car.svg',
                'icon_url'            => 'uploads/gifts/03_super_car.svg',
                'animation_url'       => 'uploads/gifts/03_super_car.svg',
                'animation_asset_url' => 'uploads/gifts/03_super_car.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 3,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Ultra luxury speed supercar zooming across the live room',
            ],
            [
                'name'                => 'Space Rocket',
                'slug'                => 'rocket',
                'coins'               => 10000,
                'coin_price'          => 10000,
                'category'            => 'svip',
                'badge'               => 'ROCKET',
                'image'               => 'uploads/gifts/04_rocket.svg',
                'icon_url'            => 'uploads/gifts/04_rocket.svg',
                'animation_url'       => 'uploads/gifts/04_rocket.svg',
                'animation_asset_url' => 'uploads/gifts/04_rocket.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 4,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'High-speed cosmic rocket launching into deep space with thruster fire',
            ],
            [
                'name'                => 'Love Castle',
                'slug'                => 'love_castle',
                'coins'               => 20000,
                'coin_price'          => 20000,
                'category'            => 'svip',
                'badge'               => 'CASTLE',
                'image'               => 'uploads/gifts/05_love_castle.svg',
                'icon_url'            => 'uploads/gifts/05_love_castle.svg',
                'animation_url'       => 'uploads/gifts/05_love_castle.svg',
                'animation_asset_url' => 'uploads/gifts/05_love_castle.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 5,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Enchanted romantic fairy-tale love fortress',
            ],
            [
                'name'                => 'Royal Crown',
                'slug'                => 'crown',
                'coins'               => 3000,
                'coin_price'          => 3000,
                'category'            => 'luxury',
                'badge'               => 'CROWN',
                'image'               => 'uploads/gifts/06_crown.svg',
                'icon_url'            => 'uploads/gifts/06_crown.svg',
                'animation_url'       => 'uploads/gifts/06_crown.svg',
                'animation_asset_url' => 'uploads/gifts/06_crown.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 6,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Pure 24K gold imperial crown with diamond embedded jewels',
            ],
            [
                'name'                => 'Luxury Yacht',
                'slug'                => 'yacht',
                'coins'               => 15000,
                'coin_price'          => 15000,
                'category'            => 'svip',
                'badge'               => 'YACHT',
                'image'               => 'uploads/gifts/07_yacht.svg',
                'icon_url'            => 'uploads/gifts/07_yacht.svg',
                'animation_url'       => 'uploads/gifts/07_yacht.svg',
                'animation_asset_url' => 'uploads/gifts/07_yacht.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 7,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Mega cruise VIP private yacht sailing through ocean waves',
            ],
            [
                'name'                => 'Cosmic Galaxy',
                'slug'                => 'galaxy',
                'coins'               => 30000,
                'coin_price'          => 30000,
                'category'            => 'svip',
                'badge'               => 'GALAXY',
                'image'               => 'uploads/gifts/08_galaxy.svg',
                'icon_url'            => 'uploads/gifts/08_galaxy.svg',
                'animation_url'       => 'uploads/gifts/08_galaxy.svg',
                'animation_asset_url' => 'uploads/gifts/08_galaxy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 8,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Rotating spiral cosmos with nebula stars and orbiting comets',
            ],
            [
                'name'                => 'Golden Phoenix',
                'slug'                => 'phoenix',
                'coins'               => 25000,
                'coin_price'          => 25000,
                'category'            => 'svip',
                'badge'               => 'PHOENIX',
                'image'               => 'uploads/gifts/09_phoenix.svg',
                'icon_url'            => 'uploads/gifts/09_phoenix.svg',
                'animation_url'       => 'uploads/gifts/09_phoenix.svg',
                'animation_asset_url' => 'uploads/gifts/09_phoenix.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 9,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Majestic mystical fire phoenix spreading blazing wings',
            ],
            [
                'name'                => 'Fire Dragon 3D',
                'slug'                => 'dragon',
                'coins'               => 20000,
                'coin_price'          => 20000,
                'category'            => 'svip',
                'badge'               => 'DRAGON',
                'image'               => 'uploads/gifts/10_dragon.svg',
                'icon_url'            => 'uploads/gifts/10_dragon.svg',
                'animation_url'       => 'uploads/gifts/10_dragon.svg',
                'animation_asset_url' => 'uploads/gifts/10_dragon.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 10,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Legendary oriental emerald dragon surging with lightning and flame',
            ],
            [
                'name'                => 'One Piece Treasure Box',
                'slug'                => 'treasure_box',
                'coins'               => 888,
                'coin_price'          => 888,
                'category'            => 'lucky',
                'badge'               => '888 LUCK',
                'image'               => 'uploads/gifts/11_treasure_box.svg',
                'icon_url'            => 'uploads/gifts/11_treasure_box.svg',
                'animation_url'       => 'uploads/gifts/11_treasure_box.svg',
                'animation_asset_url' => 'uploads/gifts/11_treasure_box.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 11,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Gleaming pirate chest bursting with gold coins and radiant diamonds',
            ],
            [
                'name'                => 'Magic Diamond Ring',
                'slug'                => 'magic_ring',
                'coins'               => 1314,
                'coin_price'          => 1314,
                'category'            => 'romantic',
                'badge'               => '1314 FOREVER',
                'image'               => 'uploads/gifts/12_magic_ring.svg',
                'icon_url'            => 'uploads/gifts/12_magic_ring.svg',
                'animation_url'       => 'uploads/gifts/12_magic_ring.svg',
                'animation_asset_url' => 'uploads/gifts/12_magic_ring.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 12,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Eternal love proposal solitaire diamond ring with halo sparkle',
            ],
            [
                'name'                => 'Celestial Angel Wings',
                'slug'                => 'angel_wings',
                'coins'               => 6666,
                'coin_price'          => 6666,
                'category'            => 'luxury',
                'badge'               => 'ANGEL',
                'image'               => 'uploads/gifts/13_angel_wings.svg',
                'icon_url'            => 'uploads/gifts/13_angel_wings.svg',
                'animation_url'       => 'uploads/gifts/13_angel_wings.svg',
                'animation_asset_url' => 'uploads/gifts/13_angel_wings.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 13,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Glowing celestial golden angel wings with soft feather ripples',
            ],
            [
                'name'                => 'Romantic Hot Kiss',
                'slug'                => 'kiss',
                'coins'               => 99,
                'coin_price'          => 99,
                'category'            => 'romantic',
                'badge'               => 'KISS',
                'image'               => 'uploads/gifts/14_kiss.svg',
                'icon_url'            => 'uploads/gifts/14_kiss.svg',
                'animation_url'       => 'uploads/gifts/14_kiss.svg',
                'animation_asset_url' => 'uploads/gifts/14_kiss.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 14,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Vibrant ruby lips blowing dynamic glowing love hearts',
            ],
            [
                'name'                => 'Grand Fireworks Celebration',
                'slug'                => 'fireworks',
                'coins'               => 2888,
                'coin_price'          => 2888,
                'category'            => 'party',
                'badge'               => 'PARTY',
                'image'               => 'uploads/gifts/15_fireworks.svg',
                'icon_url'            => 'uploads/gifts/15_fireworks.svg',
                'animation_url'       => 'uploads/gifts/15_fireworks.svg',
                'animation_asset_url' => 'uploads/gifts/15_fireworks.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 15,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Festive multi-color fireworks blast with cascading particle sparks',
            ],
            [
                'name'                => 'Cute Panda Delight',
                'slug'                => 'panda',
                'coins'               => 199,
                'coin_price'          => 199,
                'category'            => 'cute',
                'badge'               => 'PANDA',
                'image'               => 'uploads/gifts/16_panda.svg',
                'icon_url'            => 'uploads/gifts/16_panda.svg',
                'animation_url'       => 'uploads/gifts/16_panda.svg',
                'animation_asset_url' => 'uploads/gifts/16_panda.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 16,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Adorable cuddly panda chewing fresh bamboo shoot',
            ],
            [
                'name'                => 'Korean Finger Heart',
                'slug'                => 'finger_heart',
                'coins'               => 66,
                'coin_price'          => 66,
                'category'            => 'romantic',
                'badge'               => 'SARANGHAE',
                'image'               => 'uploads/gifts/17_finger_heart.svg',
                'icon_url'            => 'uploads/gifts/17_finger_heart.svg',
                'animation_url'       => 'uploads/gifts/17_finger_heart.svg',
                'animation_asset_url' => 'uploads/gifts/17_finger_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 17,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Trendy K-pop finger heart gesture bursting with pink neon energy',
            ],
            [
                'name'                => 'Sacred Angel Heart',
                'slug'                => 'angel_heart',
                'coins'               => 3333,
                'coin_price'          => 3333,
                'category'            => 'romantic',
                'badge'               => 'SACRED',
                'image'               => 'uploads/gifts/18_angel_heart.svg',
                'icon_url'            => 'uploads/gifts/18_angel_heart.svg',
                'animation_url'       => 'uploads/gifts/18_angel_heart.svg',
                'animation_asset_url' => 'uploads/gifts/18_angel_heart.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 18,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Ruby heart flanked with glowing golden feathers and halo',
            ],
            [
                'name'                => '1000 Rose Bouquet',
                'slug'                => 'rose_bouquet',
                'coins'               => 999,
                'coin_price'          => 999,
                'category'            => 'romantic',
                'badge'               => '999 ROSES',
                'image'               => 'uploads/gifts/19_rose_bouquet.svg',
                'icon_url'            => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_url'       => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_asset_url' => 'uploads/gifts/19_rose_bouquet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 19,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Giant luxury red velvet rose bouquet wrapped in gold ribbon',
            ],
            [
                'name'                => 'Super Luxury Yacht 3D',
                'slug'                => 'luxury_yacht',
                'coins'               => 18888,
                'coin_price'          => 18888,
                'category'            => 'svip',
                'badge'               => 'SUPER YACHT',
                'image'               => 'uploads/gifts/20_luxury_yacht.svg',
                'icon_url'            => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_url'       => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_asset_url' => 'uploads/gifts/20_luxury_yacht.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 20,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Twin-deck super yacht cruise gliding across twilight waters',
            ],
            [
                'name'                => 'Diamond Rain Shower',
                'slug'                => 'diamond_shower',
                'coins'               => 7777,
                'coin_price'          => 7777,
                'category'            => 'wealth',
                'badge'               => 'DIAMOND RAIN',
                'image'               => 'uploads/gifts/21_diamond_shower.svg',
                'icon_url'            => 'uploads/gifts/21_diamond_shower.svg',
                'animation_url'       => 'uploads/gifts/21_diamond_shower.svg',
                'animation_asset_url' => 'uploads/gifts/21_diamond_shower.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 21,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Cascading shower of brilliant sparkling blue and white diamonds',
            ],
            [
                'name'                => 'Emperor Crown',
                'slug'                => 'royal_crown',
                'coins'               => 8888,
                'coin_price'          => 8888,
                'category'            => 'luxury',
                'badge'               => 'EMPEROR',
                'image'               => 'uploads/gifts/22_royal_crown.svg',
                'icon_url'            => 'uploads/gifts/22_royal_crown.svg',
                'animation_url'       => 'uploads/gifts/22_royal_crown.svg',
                'animation_asset_url' => 'uploads/gifts/22_royal_crown.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 22,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Supreme monarchy emperor crown studded with precious gems',
            ],
            [
                'name'                => 'Supernova Rocket',
                'slug'                => 'space_rocket',
                'coins'               => 12000,
                'coin_price'          => 12000,
                'category'            => 'svip',
                'badge'               => 'SUPERNOVA',
                'image'               => 'uploads/gifts/23_rocket.svg',
                'icon_url'            => 'uploads/gifts/23_rocket.svg',
                'animation_url'       => 'uploads/gifts/23_rocket.svg',
                'animation_asset_url' => 'uploads/gifts/23_rocket.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 23,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Interstellar rocket blazing with plasma boost trail',
            ],
            [
                'name'                => 'Deep Space Galaxy',
                'slug'                => 'space_galaxy',
                'coins'               => 35000,
                'coin_price'          => 35000,
                'category'            => 'svip',
                'badge'               => 'UNIVERSE',
                'image'               => 'uploads/gifts/24_galaxy.svg',
                'icon_url'            => 'uploads/gifts/24_galaxy.svg',
                'animation_url'       => 'uploads/gifts/24_galaxy.svg',
                'animation_asset_url' => 'uploads/gifts/24_galaxy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 24,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Epic spinning cosmic vortex with orbital planetary rings',
            ],
            [
                'name'                => 'Mystic Crescent Moon',
                'slug'                => 'glowing_moon',
                'coins'               => 4500,
                'coin_price'          => 4500,
                'category'            => 'romantic',
                'badge'               => 'MOONLIGHT',
                'image'               => 'uploads/gifts/25_moon.svg',
                'icon_url'            => 'uploads/gifts/25_moon.svg',
                'animation_url'       => 'uploads/gifts/25_moon.svg',
                'animation_asset_url' => 'uploads/gifts/25_moon.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 25,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Dreamy silver crescent moon glowing with stardust clouds',
            ],
            [
                'name'                => 'Radiant Golden Sun',
                'slug'                => 'golden_sun',
                'coins'               => 9999,
                'coin_price'          => 9999,
                'category'            => 'wealth',
                'badge'               => 'SOLAR',
                'image'               => 'uploads/gifts/26_golden_sun.svg',
                'icon_url'            => 'uploads/gifts/26_golden_sun.svg',
                'animation_url'       => 'uploads/gifts/26_golden_sun.svg',
                'animation_asset_url' => 'uploads/gifts/26_golden_sun.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 26,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Golden solar flare aura emanating majestic warmth and power',
            ],
            [
                'name'                => 'Ringed Celestial Planet',
                'slug'                => 'cosmic_planet',
                'coins'               => 16000,
                'coin_price'          => 16000,
                'category'            => 'svip',
                'badge'               => 'SATURN',
                'image'               => 'uploads/gifts/27_planet.svg',
                'icon_url'            => 'uploads/gifts/27_planet.svg',
                'animation_url'       => 'uploads/gifts/27_planet.svg',
                'animation_asset_url' => 'uploads/gifts/27_planet.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 27,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Saturn-like giant celestial body surrounded by spinning rings',
            ],
            [
                'name'                => 'World Champion Cup 2026',
                'slug'                => 'champion_trophy',
                'coins'               => 2026,
                'coin_price'          => 2026,
                'category'            => 'party',
                'badge'               => '2026 CUP',
                'image'               => 'uploads/gifts/28_champion_trophy.svg',
                'icon_url'            => 'uploads/gifts/28_champion_trophy.svg',
                'animation_url'       => 'uploads/gifts/28_champion_trophy.svg',
                'animation_asset_url' => 'uploads/gifts/28_champion_trophy.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 28,
                'is_active'           => true,
                'is_broadcast'        => false,
                'description'         => 'Shining golden trophy cup for the ultimate stream champion',
            ],
            [
                'name'                => 'Diamond Fortress Castle',
                'slug'                => 'diamond_castle',
                'coins'               => 40000,
                'coin_price'          => 40000,
                'category'            => 'svip',
                'badge'               => '40K CASTLE',
                'image'               => 'uploads/gifts/29_diamond_castle.svg',
                'icon_url'            => 'uploads/gifts/29_diamond_castle.svg',
                'animation_url'       => 'uploads/gifts/29_diamond_castle.svg',
                'animation_asset_url' => 'uploads/gifts/29_diamond_castle.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 29,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Fairy tale crystal diamond fortress with shimmering towers',
            ],
            [
                'name'                => 'Imperial Royal Palace',
                'slug'                => 'imperial_royal_palace',
                'coins'               => 50000,
                'coin_price'          => 50000,
                'category'            => 'svip',
                'badge'               => '50K PALACE',
                'image'               => 'uploads/gifts/30_royal_palace.svg',
                'icon_url'            => 'uploads/gifts/30_royal_palace.svg',
                'animation_url'       => 'uploads/gifts/30_royal_palace.svg',
                'animation_asset_url' => 'uploads/gifts/30_royal_palace.svg',
                'animation_type'      => 'svg',
                'format'              => 'svg',
                'display_type'        => 'fullscreen',
                'sort_order'          => 30,
                'is_active'           => true,
                'is_broadcast'        => true,
                'description'         => 'Grand imperial royal palace with fireworks and gold gates',
            ],
        ];

        foreach ($gifts as $giftData) {
            Gift::create($giftData);
        }

        // 2. Sync Coin Packages with new Diamond Burst Motion Icons
        $coinPackages = [
            [
                'title' => 'Starter Pack',
                'coins' => 7560,
                'bonus_coins' => 0,
                'price' => 150.00,
                'currency' => 'BDT',
                'badge' => '50% off',
                'badge_color' => 'danger',
                'icon_url' => 'uploads/coin_packages/burst.png',
                'animation_url' => 'uploads/coin_packages/burst_animated.svg',
                'format' => 'svg',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Basic Pack',
                'coins' => 8100,
                'bonus_coins' => 0,
                'price' => 300.00,
                'currency' => 'BDT',
                'badge' => '17% off',
                'badge_color' => 'pink',
                'icon_url' => 'uploads/coin_packages/diamond_orb.png',
                'animation_url' => 'uploads/coin_packages/diamond_orb_animated.svg',
                'format' => 'svg',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'Popular Pack',
                'coins' => 16380,
                'bonus_coins' => 0,
                'price' => 600.00,
                'currency' => 'BDT',
                'badge' => '17% off',
                'badge_color' => 'pink',
                'icon_url' => 'uploads/coin_packages/diamond_crown.png',
                'animation_url' => 'uploads/coin_packages/diamond_crown_animated.svg',
                'format' => 'svg',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'Super Pack',
                'coins' => 32940,
                'bonus_coins' => 0,
                'price' => 1200.00,
                'currency' => 'BDT',
                'badge' => '30% off',
                'badge_color' => 'pink',
                'icon_url' => 'uploads/coin_packages/crystal_crown.png',
                'animation_url' => 'uploads/coin_packages/crystal_crown_animated.svg',
                'format' => 'svg',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'Mega Pack',
                'coins' => 66600,
                'bonus_coins' => 0,
                'price' => 2400.00,
                'currency' => 'BDT',
                'badge' => '60% off',
                'badge_color' => 'pink',
                'icon_url' => 'uploads/coin_packages/magic_bag.png',
                'animation_url' => 'uploads/coin_packages/magic_bag_animated.svg',
                'format' => 'svg',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'VIP King Pack',
                'coins' => 167400,
                'bonus_coins' => 0,
                'price' => 6100.00,
                'currency' => 'BDT',
                'badge' => '80% off',
                'badge_color' => 'danger',
                'icon_url' => 'uploads/coin_packages/royal_chest.png',
                'animation_url' => 'uploads/coin_packages/royal_chest_animated.svg',
                'format' => 'svg',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
        ];

        CoinPackage::truncate();

        foreach ($coinPackages as $pkg) {
            CoinPackage::create($pkg);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // No down migration needed
    }
};
