<?php

require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Gift;

$allGifts = [
    // ==========================================
    // 🔥 1. HOT GIFTS (Trending, CP & Popular)
    // ==========================================
    [
        'name'           => 'Trophy Cup',
        'coins'          => 500,
        'coin_price'     => 500,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/trophy_cup.svg',
        'icon_url'       => 'uploads/gifts/trophy_cup.svg',
        'animation_url'  => 'uploads/gifts/trophy_cup.svg',
        'file_url'       => 'uploads/gifts/trophy_cup.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'HOT',
        'description'    => 'Golden victory trophy cup with glowing championship sparkles.',
        'sort_order'     => 1,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Mystery Box',
        'coins'          => 888,
        'coin_price'     => 888,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/mystery_box.svg',
        'icon_url'       => 'uploads/gifts/mystery_box.svg',
        'animation_url'  => 'uploads/gifts/mystery_box.svg',
        'file_url'       => 'uploads/gifts/mystery_box.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'MUST WIN',
        'description'    => 'Must win mystery surprise box with glowing rewards.',
        'sort_order'     => 2,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'CP Love Letter',
        'coins'          => 520,
        'coin_price'     => 520,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/cp_love_letter.svg',
        'icon_url'       => 'uploads/gifts/cp_love_letter.svg',
        'animation_url'  => 'uploads/gifts/cp_love_letter.svg',
        'file_url'       => 'uploads/gifts/cp_love_letter.svg',
        'animation_type' => 'flying_envelope',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => '520 LOVE',
        'description'    => 'Romantic couple sealed love confession letter.',
        'sort_order'     => 3,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'In My Hands',
        'coins'          => 1314,
        'coin_price'     => 1314,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/in_my_hands.svg',
        'icon_url'       => 'uploads/gifts/in_my_hands.svg',
        'animation_url'  => 'uploads/gifts/in_my_hands.svg',
        'file_url'       => 'uploads/gifts/in_my_hands.svg',
        'animation_type' => 'particle_hearts',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'SWEET',
        'description'    => 'Couple holding hands tightly with glowing starry hearts.',
        'sort_order'     => 4,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'CP Romantic Kiss',
        'coins'          => 999,
        'coin_price'     => 999,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/cp_romantic_kiss.svg',
        'icon_url'       => 'uploads/gifts/cp_romantic_kiss.svg',
        'animation_url'  => 'uploads/gifts/cp_romantic_kiss.svg',
        'file_url'       => 'uploads/gifts/cp_romantic_kiss.svg',
        'animation_type' => 'particle_hearts',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'HOT KISS',
        'description'    => 'Sweet couple romantic kiss with floating beating hearts.',
        'sort_order'     => 5,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Golden Couple',
        'coins'          => 2000,
        'coin_price'     => 2000,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/romantic_couple.png',
        'icon_url'       => 'uploads/gifts/romantic_couple.png',
        'animation_url'  => 'uploads/gifts/romantic_couple.png',
        'file_url'       => 'uploads/gifts/romantic_couple.png',
        'animation_type' => 'romantic_glow',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'COUPLE',
        'description'    => 'Golden animated romantic couple with sparkle effects.',
        'sort_order'     => 6,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Jackpot Slot Machine',
        'coins'          => 777,
        'coin_price'     => 777,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/slot_machine.svg',
        'icon_url'       => 'uploads/gifts/slot_machine.svg',
        'animation_url'  => 'uploads/gifts/slot_machine.svg',
        'file_url'       => 'uploads/gifts/slot_machine.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'LUCKY 777',
        'description'    => 'Triple 7 jackpot slot machine spinning with coins.',
        'sort_order'     => 7,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Celebrity Red Carpet',
        'coins'          => 5200,
        'coin_price'     => 5200,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/sunset_couple.svg',
        'icon_url'       => 'uploads/gifts/sunset_couple.svg',
        'animation_url'  => 'uploads/gifts/sunset_couple.svg',
        'file_url'       => 'uploads/gifts/sunset_couple.svg',
        'animation_type' => 'cinematic_sunset',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'CELEBRITY',
        'description'    => 'VIP celebrity couple on luxury red carpet.',
        'sort_order'     => 8,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Best CP Star',
        'coins'          => 3333,
        'coin_price'     => 3333,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/shooting_star_wish.svg',
        'icon_url'       => 'uploads/gifts/shooting_star_wish.svg',
        'animation_url'  => 'uploads/gifts/shooting_star_wish.svg',
        'file_url'       => 'uploads/gifts/shooting_star_wish.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'CP STAR',
        'description'    => 'Radiant glowing star award for the best live couple.',
        'sort_order'     => 9,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Run To Love',
        'coins'          => 5550,
        'coin_price'     => 5550,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/romantic_couple.svg',
        'icon_url'       => 'uploads/gifts/romantic_couple.svg',
        'animation_url'  => 'uploads/gifts/romantic_couple.svg',
        'file_url'       => 'uploads/gifts/romantic_couple.svg',
        'animation_type' => 'fullscreen_castle_aurora',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'HOT 5.55K',
        'description'    => 'Romantic animation of running across starlight into a warm hug.',
        'sort_order'     => 10,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Superstar Stage',
        'coins'          => 6666,
        'coin_price'     => 6666,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/emperor_golden_throne.svg',
        'icon_url'       => 'uploads/gifts/emperor_golden_throne.svg',
        'animation_url'  => 'uploads/gifts/emperor_golden_throne.svg',
        'file_url'       => 'uploads/gifts/emperor_golden_throne.svg',
        'animation_type' => 'crown_descend_gold',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'SUPERSTAR',
        'description'    => 'Illuminated stage spotlight honoring the live room superstar.',
        'sort_order'     => 11,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'World Cup Champion 2026',
        'coins'          => 2026,
        'coin_price'     => 2026,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/world_cup_trophy.svg',
        'icon_url'       => 'uploads/gifts/world_cup_trophy.svg',
        'animation_url'  => 'uploads/gifts/world_cup_trophy.svg',
        'file_url'       => 'uploads/gifts/world_cup_trophy.svg',
        'animation_type' => 'fullscreen_fireworks',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '2026 CUP',
        'description'    => 'Golden FIFA World Cup Championship trophy celebration.',
        'sort_order'     => 12,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Taj Mahal Wonder',
        'coins'          => 35000,
        'coin_price'     => 35000,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/taj_mahal_palace.svg',
        'icon_url'       => 'uploads/gifts/taj_mahal_palace.svg',
        'animation_url'  => 'uploads/gifts/taj_mahal_palace.svg',
        'file_url'       => 'uploads/gifts/taj_mahal_palace.svg',
        'animation_type' => 'fullscreen_castle_aurora',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '35K PALACE',
        'description'    => 'Monumental Taj Mahal marble palace with reflecting pool.',
        'sort_order'     => 13,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'I Am Rich Cash Shower',
        'coins'          => 9999,
        'coin_price'     => 9999,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/i_am_rich_cash.svg',
        'icon_url'       => 'uploads/gifts/i_am_rich_cash.svg',
        'animation_url'  => 'uploads/gifts/i_am_rich_cash.svg',
        'file_url'       => 'uploads/gifts/i_am_rich_cash.svg',
        'animation_type' => 'mouse_coin_rush',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'I AM RICH',
        'description'    => 'Floating stacks of gold dollars raining over the entire screen.',
        'sort_order'     => 14,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Flaming Red Chili',
        'coins'          => 99,
        'coin_price'     => 99,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/hot_chili_pepper.svg',
        'icon_url'       => 'uploads/gifts/hot_chili_pepper.svg',
        'animation_url'  => 'uploads/gifts/hot_chili_pepper.svg',
        'file_url'       => 'uploads/gifts/hot_chili_pepper.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'HOT 🔥',
        'description'    => 'Spicy flaming red hot chili pepper.',
        'sort_order'     => 15,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Golden Lucky Egg',
        'coins'          => 888,
        'coin_price'     => 888,
        'category'       => 'hot',
        'image'          => 'uploads/gifts/golden_egg_crack.svg',
        'icon_url'       => 'uploads/gifts/golden_egg_crack.svg',
        'animation_url'  => 'uploads/gifts/golden_egg_crack.svg',
        'file_url'       => 'uploads/gifts/golden_egg_crack.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'LUCKY 888',
        'description'    => 'Golden egg cracking open with fireworks and coins.',
        'sort_order'     => 16,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],

    // ==========================================
    // 🍀 2. LUCKY GIFTS (Jackpot, Wheels & Multipliers)
    // ==========================================
    [
        'name'           => 'Lucky Mystery Chest',
        'coins'          => 888,
        'coin_price'     => 888,
        'category'       => 'lucky',
        'image'          => 'uploads/gifts/mystery_box.svg',
        'icon_url'       => 'uploads/gifts/mystery_box.svg',
        'animation_url'  => 'uploads/gifts/mystery_box.svg',
        'file_url'       => 'uploads/gifts/mystery_box.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'WIN x500',
        'description'    => 'Lucky mystery box with random coin multiplier drops.',
        'sort_order'     => 17,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Lucky Kiss Lips',
        'coins'          => 299,
        'coin_price'     => 299,
        'category'       => 'lucky',
        'image'          => 'uploads/gifts/romantic_kiss_gift.svg',
        'icon_url'       => 'uploads/gifts/romantic_kiss_gift.svg',
        'animation_url'  => 'uploads/gifts/romantic_kiss_gift.svg',
        'file_url'       => 'uploads/gifts/romantic_kiss_gift.svg',
        'animation_type' => 'particle_hearts',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'LUCKY',
        'description'    => 'Kiss lips with lucky fortune sparkles.',
        'sort_order'     => 18,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'TNT Bombastic Blast',
        'coins'          => 333,
        'coin_price'     => 333,
        'category'       => 'lucky',
        'image'          => 'uploads/gifts/volcano_eruption.svg',
        'icon_url'       => 'uploads/gifts/volcano_eruption.svg',
        'animation_url'  => 'uploads/gifts/volcano_eruption.svg',
        'file_url'       => 'uploads/gifts/volcano_eruption.svg',
        'animation_type' => 'rocket_blastoff',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'BOOM',
        'description'    => 'Explosive cartoon TNT bomb with celebration blast.',
        'sort_order'     => 19,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Lucky Four Leaf Clover',
        'coins'          => 500,
        'coin_price'     => 500,
        'category'       => 'lucky',
        'image'          => 'uploads/gifts/lucky_four_clover.svg',
        'icon_url'       => 'uploads/gifts/lucky_four_clover.svg',
        'animation_url'  => 'uploads/gifts/lucky_four_clover.svg',
        'file_url'       => 'uploads/gifts/lucky_four_clover.svg',
        'animation_type' => 'flying_petals',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'CLOVER',
        'description'    => 'Enchanted 4-leaf emerald clover bringing high fortune.',
        'sort_order'     => 20,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Lucky Gold Mouse',
        'coins'          => 888,
        'coin_price'     => 888,
        'category'       => 'lucky',
        'image'          => 'uploads/gifts/lucky_gold_mouse.svg',
        'icon_url'       => 'uploads/gifts/lucky_gold_mouse.svg',
        'animation_url'  => 'uploads/gifts/lucky_gold_mouse.svg',
        'file_url'       => 'uploads/gifts/lucky_gold_mouse.svg',
        'animation_type' => 'mouse_coin_rush',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => '888 COINS',
        'description'    => 'Cute golden lucky mouse bringing chests of fortune coins.',
        'sort_order'     => 21,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Funny Whack Hammer',
        'coins'          => 50,
        'coin_price'     => 50,
        'category'       => 'lucky',
        'image'          => 'uploads/gifts/thor_hammer_strike.svg',
        'icon_url'       => 'uploads/gifts/thor_hammer_strike.svg',
        'animation_url'  => 'uploads/gifts/thor_hammer_strike.svg',
        'file_url'       => 'uploads/gifts/thor_hammer_strike.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'FUNNY',
        'description'    => 'Cartoon squeaky hammer for playful banter.',
        'sort_order'     => 22,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],

    // ==========================================
    // 👑 3. SVIP GIFTS (Ultra High Tier Luxury)
    // ==========================================
    [
        'name'           => 'Bollywood Super Diva',
        'coins'          => 18888,
        'coin_price'     => 18888,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/starlight_serenade.svg',
        'icon_url'       => 'uploads/gifts/starlight_serenade.svg',
        'animation_url'  => 'uploads/gifts/starlight_serenade.svg',
        'file_url'       => 'uploads/gifts/starlight_serenade.svg',
        'animation_type' => 'crown_descend_gold',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'DIVA SVIP',
        'description'    => 'Glamorous cinema star receiving a grand standing ovation.',
        'sort_order'     => 23,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Royal Bengal Tiger',
        'coins'          => 25000,
        'coin_price'     => 25000,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/bengal_tiger_roar.svg',
        'icon_url'       => 'uploads/gifts/bengal_tiger_roar.svg',
        'animation_url'  => 'uploads/gifts/bengal_tiger_roar.svg',
        'file_url'       => 'uploads/gifts/bengal_tiger_roar.svg',
        'animation_type' => 'dragon_roar_fire',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'SVIP TIGER',
        'description'    => 'Roaring fierce Royal Bengal tiger with glowing emerald eyes.',
        'sort_order'     => 24,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Luxury Roadster Convertible',
        'coins'          => 33333,
        'coin_price'     => 33333,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/royal_limousine.svg',
        'icon_url'       => 'uploads/gifts/royal_limousine.svg',
        'animation_url'  => 'uploads/gifts/royal_limousine.svg',
        'file_url'       => 'uploads/gifts/royal_limousine.svg',
        'animation_type' => 'drive_in_drift',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'ROADSTER',
        'description'    => 'Open-top gold plated luxury convertible gliding on screen.',
        'sort_order'     => 25,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Imperial Royal Elephant',
        'coins'          => 40000,
        'coin_price'     => 40000,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/royal_elephant_howdah.svg',
        'icon_url'       => 'uploads/gifts/royal_elephant_howdah.svg',
        'animation_url'  => 'uploads/gifts/royal_elephant_howdah.svg',
        'file_url'       => 'uploads/gifts/royal_elephant_howdah.svg',
        'animation_type' => 'fullscreen_castle_aurora',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'ROYAL 40K',
        'description'    => 'Regal decorated elephant with golden howdah and jewel garlands.',
        'sort_order'     => 26,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Mayurpankhi Peacock Chariot',
        'coins'          => 45000,
        'coin_price'     => 45000,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/peacock_dance.svg',
        'icon_url'       => 'uploads/gifts/peacock_dance.svg',
        'animation_url'  => 'uploads/gifts/peacock_dance.svg',
        'file_url'       => 'uploads/gifts/peacock_dance.svg',
        'animation_type' => 'phoenix_flight',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'PEACOCK',
        'description'    => 'Mythological royal peacock boat sailing across starry waters.',
        'sort_order'     => 27,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Sky Floating Aurora Castle',
        'coins'          => 75000,
        'coin_price'     => 75000,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/crystal_castle.svg',
        'icon_url'       => 'uploads/gifts/crystal_castle.svg',
        'animation_url'  => 'uploads/gifts/crystal_castle.svg',
        'file_url'       => 'uploads/gifts/crystal_castle.svg',
        'animation_type' => 'fullscreen_castle_aurora',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'SKY CASTLE',
        'description'    => 'Enchanted celestial citadel floating above clouds with aurora beams.',
        'sort_order'     => 28,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Grand Festival of Lights',
        'coins'          => 60000,
        'coin_price'     => 60000,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/heart_fireworks_gift.svg',
        'icon_url'       => 'uploads/gifts/heart_fireworks_gift.svg',
        'animation_url'  => 'uploads/gifts/heart_fireworks_gift.svg',
        'file_url'       => 'uploads/gifts/heart_fireworks_gift.svg',
        'animation_type' => 'fullscreen_fireworks',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '60K FEST',
        'description'    => 'Grand celebration lanterns and full screen fireworks show.',
        'sort_order'     => 29,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Imperial Golden Banquet',
        'coins'          => 5000,
        'coin_price'     => 5000,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/candlelight_dinner.svg',
        'icon_url'       => 'uploads/gifts/candlelight_dinner.svg',
        'animation_url'  => 'uploads/gifts/candlelight_dinner.svg',
        'file_url'       => 'uploads/gifts/candlelight_dinner.svg',
        'animation_type' => 'romantic_glow',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'FEAST',
        'description'    => 'Imperial golden feast with delicacies and gold cutlery.',
        'sort_order'     => 30,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Enchanted Forever Rose',
        'coins'          => 13140,
        'coin_price'     => 13140,
        'category'       => 'svip',
        'image'          => 'uploads/gifts/rose_bouquet_gift.svg',
        'icon_url'       => 'uploads/gifts/rose_bouquet_gift.svg',
        'animation_url'  => 'uploads/gifts/rose_bouquet_gift.svg',
        'file_url'       => 'uploads/gifts/rose_bouquet_gift.svg',
        'animation_type' => 'flying_petals',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'FOREVER 1314',
        'description'    => 'Crystal dome enclosed eternal glowing enchanted rose.',
        'sort_order'     => 31,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // 💖 4. INTIMACY GIFTS (Love, Romance & Couples)
    // ==========================================
    [
        'name'           => 'Vintage Love Letter',
        'coins'          => 520,
        'coin_price'     => 520,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/love_mailbox.svg',
        'icon_url'       => 'uploads/gifts/love_mailbox.svg',
        'animation_url'  => 'uploads/gifts/love_mailbox.svg',
        'file_url'       => 'uploads/gifts/love_mailbox.svg',
        'animation_type' => 'flying_envelope',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'LOVE 520',
        'description'    => 'Vintage romantic love letter delivered by lovebirds.',
        'sort_order'     => 32,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'My World in My Hands',
        'coins'          => 1314,
        'coin_price'     => 1314,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/in_my_hands.svg',
        'icon_url'       => 'uploads/gifts/in_my_hands.svg',
        'animation_url'  => 'uploads/gifts/in_my_hands.svg',
        'file_url'       => 'uploads/gifts/in_my_hands.svg',
        'animation_type' => 'particle_hearts',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => '1314',
        'description'    => 'Two lovers entwined hands with heartbeat pulse.',
        'sort_order'     => 33,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Romance Memory Album',
        'coins'          => 999,
        'coin_price'     => 999,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/teddy_bear_gift.svg',
        'icon_url'       => 'uploads/gifts/teddy_bear_gift.svg',
        'animation_url'  => 'uploads/gifts/teddy_bear_gift.svg',
        'file_url'       => 'uploads/gifts/teddy_bear_gift.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'MEMORIES',
        'description'    => 'Flipping photo album displaying glowing memories.',
        'sort_order'     => 34,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => '5-Star Candlelight Dinner',
        'coins'          => 2000,
        'coin_price'     => 2000,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/candlelight_dinner.svg',
        'icon_url'       => 'uploads/gifts/candlelight_dinner.svg',
        'animation_url'  => 'uploads/gifts/candlelight_dinner.svg',
        'file_url'       => 'uploads/gifts/candlelight_dinner.svg',
        'animation_type' => 'romantic_glow',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'SWEET',
        'description'    => 'Romantic 5-star private candlelight table for two.',
        'sort_order'     => 35,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Sunset Couple Walk',
        'coins'          => 5200,
        'coin_price'     => 5200,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/sunset_couple.svg',
        'icon_url'       => 'uploads/gifts/sunset_couple.svg',
        'animation_url'  => 'uploads/gifts/sunset_couple.svg',
        'file_url'       => 'uploads/gifts/sunset_couple.svg',
        'animation_type' => 'cinematic_sunset',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'ETERNAL',
        'description'    => 'Lovers walking along warm sunset beach waves.',
        'sort_order'     => 36,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Midnight Lovers Moon',
        'coins'          => 9999,
        'coin_price'     => 9999,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/midnight_lovers.svg',
        'icon_url'       => 'uploads/gifts/midnight_lovers.svg',
        'animation_url'  => 'uploads/gifts/midnight_lovers.svg',
        'file_url'       => 'uploads/gifts/midnight_lovers.svg',
        'animation_type' => 'celestial_moon',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'MOONLIGHT',
        'description'    => 'Embracing lovers sitting on a crescent moon among stars.',
        'sort_order'     => 37,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Royal Romance Carriage',
        'coins'          => 13140,
        'coin_price'     => 13140,
        'category'       => 'intimacy',
        'image'          => 'uploads/gifts/vintage_romance.svg',
        'icon_url'       => 'uploads/gifts/vintage_romance.svg',
        'animation_url'  => 'uploads/gifts/vintage_romance.svg',
        'file_url'       => 'uploads/gifts/vintage_romance.svg',
        'animation_type' => 'royal_carriage',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'ROYAL 13.14K',
        'description'    => 'White horse royal carriage with petal cascade.',
        'sort_order'     => 38,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // 💰 5. WEALTH GIFTS (Billionaires, Gold & Mansions)
    // ==========================================
    [
        'name'           => 'Wealth Golden Ingot',
        'coins'          => 8888,
        'coin_price'     => 8888,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/trophy_cup.svg',
        'icon_url'       => 'uploads/gifts/trophy_cup.svg',
        'animation_url'  => 'uploads/gifts/trophy_cup.svg',
        'file_url'       => 'uploads/gifts/trophy_cup.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'GOLD INGOT',
        'description'    => 'Pure 999.9 fine solid gold ingot bar with radiant sheen.',
        'sort_order'     => 39,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Scepter of Power & Wealth',
        'coins'          => 12000,
        'coin_price'     => 12000,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/scepter_of_power.svg',
        'icon_url'       => 'uploads/gifts/scepter_of_power.svg',
        'animation_url'  => 'uploads/gifts/scepter_of_power.svg',
        'file_url'       => 'uploads/gifts/scepter_of_power.svg',
        'animation_type' => 'crown_descend_gold',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'SCEPTER',
        'description'    => 'Imperial gold sovereign scepter crowned with a giant ruby.',
        'sort_order'     => 40,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Diamond Solitaire Ring',
        'coins'          => 9999,
        'coin_price'     => 9999,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/diamond_ring_gift.svg',
        'icon_url'       => 'uploads/gifts/diamond_ring_gift.svg',
        'animation_url'  => 'uploads/gifts/diamond_ring_gift.svg',
        'file_url'       => 'uploads/gifts/diamond_ring_gift.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'DIAMOND',
        'description'    => '24K Platinum Diamond ring gleaming with prism light.',
        'sort_order'     => 41,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Golden Space Rocket',
        'coins'          => 25000,
        'coin_price'     => 25000,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/space_rocket_gift.svg',
        'icon_url'       => 'uploads/gifts/space_rocket_gift.svg',
        'animation_url'  => 'uploads/gifts/space_rocket_gift.svg',
        'file_url'       => 'uploads/gifts/space_rocket_gift.svg',
        'animation_type' => 'rocket_blastoff',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'ROCKET 25K',
        'description'    => 'Gold titanium space rocket launching into the cosmos.',
        'sort_order'     => 42,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Heart of the Ocean Blue Diamond',
        'coins'          => 30000,
        'coin_price'     => 30000,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/diamond_perfume.svg',
        'icon_url'       => 'uploads/gifts/diamond_perfume.svg',
        'animation_url'  => 'uploads/gifts/diamond_perfume.svg',
        'file_url'       => 'uploads/gifts/diamond_perfume.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'OCEAN GEM',
        'description'    => 'Legendary 56-carat deep blue diamond radiating brilliance.',
        'sort_order'     => 43,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Billionaire Grand Estate',
        'coins'          => 50000,
        'coin_price'     => 50000,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/billionaire_mansion.svg',
        'icon_url'       => 'uploads/gifts/billionaire_mansion.svg',
        'animation_url'  => 'uploads/gifts/billionaire_mansion.svg',
        'file_url'       => 'uploads/gifts/billionaire_mansion.svg',
        'animation_type' => 'fullscreen_castle_aurora',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '50K ESTATE',
        'description'    => 'Sprawling hilltop mansion with infinity pool and supercars.',
        'sort_order'     => 44,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Golden Champion Victory Cup',
        'coins'          => 66666,
        'coin_price'     => 66666,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/holy_grail_cup.svg',
        'icon_url'       => 'uploads/gifts/holy_grail_cup.svg',
        'animation_url'  => 'uploads/gifts/holy_grail_cup.svg',
        'file_url'       => 'uploads/gifts/holy_grail_cup.svg',
        'animation_type' => 'fullscreen_fireworks',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '66.6K CUP',
        'description'    => 'Masterpiece golden trophy decorated with emeralds.',
        'sort_order'     => 45,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Diamond Crystal Palace',
        'coins'          => 100000,
        'coin_price'     => 100000,
        'category'       => 'wealth',
        'image'          => 'uploads/gifts/diamond_castle_gift.svg',
        'icon_url'       => 'uploads/gifts/diamond_castle_gift.svg',
        'animation_url'  => 'uploads/gifts/diamond_castle_gift.svg',
        'file_url'       => 'uploads/gifts/diamond_castle_gift.svg',
        'animation_type' => 'fullscreen_castle_aurora',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '100K PALACE',
        'description'    => 'Fairytale diamond palace rising with aurora and fireworks.',
        'sort_order'     => 46,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // 🎉 6. FESTIVAL GIFTS (Carnival, Eid, New Year & Holidays)
    // ==========================================
    [
        'name'           => 'Sky Blessing Lanterns',
        'coins'          => 520,
        'coin_price'     => 520,
        'category'       => 'festival',
        'image'          => 'uploads/gifts/genie_lamp.svg',
        'icon_url'       => 'uploads/gifts/genie_lamp.svg',
        'animation_url'  => 'uploads/gifts/genie_lamp.svg',
        'file_url'       => 'uploads/gifts/genie_lamp.svg',
        'animation_type' => 'mystic_smoke',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'LANTERN',
        'description'    => 'Glowing sky lanterns carrying heartfelt wishes upward.',
        'sort_order'     => 47,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Eid Mubarak Golden Crescent',
        'coins'          => 2026,
        'coin_price'     => 2026,
        'category'       => 'festival',
        'image'          => 'uploads/gifts/eid_crescent_moon.svg',
        'icon_url'       => 'uploads/gifts/eid_crescent_moon.svg',
        'animation_url'  => 'uploads/gifts/eid_crescent_moon.svg',
        'file_url'       => 'uploads/gifts/eid_crescent_moon.svg',
        'animation_type' => 'celestial_moon',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'EID MUBARAK',
        'description'    => 'Luminous crescent moon with dangling golden lantern stars.',
        'sort_order'     => 48,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Carnival Rainbow Float',
        'coins'          => 3333,
        'coin_price'     => 3333,
        'category'       => 'festival',
        'image'          => 'uploads/gifts/golden_vip_rickshaw.svg',
        'icon_url'       => 'uploads/gifts/golden_vip_rickshaw.svg',
        'animation_url'  => 'uploads/gifts/golden_vip_rickshaw.svg',
        'file_url'       => 'uploads/gifts/golden_vip_rickshaw.svg',
        'animation_type' => 'drive_in_drift',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'CARNIVAL',
        'description'    => 'Vibrant festival carnival float with music and confetti.',
        'sort_order'     => 49,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Festival Dhol Drums',
        'coins'          => 299,
        'coin_price'     => 299,
        'category'       => 'festival',
        'image'          => 'uploads/gifts/dhak_drum_festival.svg',
        'icon_url'       => 'uploads/gifts/dhak_drum_festival.svg',
        'animation_url'  => 'uploads/gifts/dhak_drum_festival.svg',
        'file_url'       => 'uploads/gifts/dhak_drum_festival.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'DHOL',
        'description'    => 'Traditional Bengali festival dhak drum with rhythmic beats.',
        'sort_order'     => 50,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'New Year 2026 Celebration',
        'coins'          => 2026,
        'coin_price'     => 2026,
        'category'       => 'festival',
        'image'          => 'uploads/gifts/heart_fireworks_gift.svg',
        'icon_url'       => 'uploads/gifts/heart_fireworks_gift.svg',
        'animation_url'  => 'uploads/gifts/heart_fireworks_gift.svg',
        'file_url'       => 'uploads/gifts/heart_fireworks_gift.svg',
        'animation_type' => 'fullscreen_fireworks',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'HAPPY 2026',
        'description'    => 'Spectacular 2026 countdown fireworks over the city skyline.',
        'sort_order'     => 51,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // 🎒 7. BAG GIFTS (Backpack & Collectible Items)
    // ==========================================
    [
        'name'           => 'Lucky Golden Tortoise',
        'coins'          => 500,
        'coin_price'     => 500,
        'category'       => 'bag',
        'image'          => 'uploads/gifts/lucky_gold_mouse.svg',
        'icon_url'       => 'uploads/gifts/lucky_gold_mouse.svg',
        'animation_url'  => 'uploads/gifts/lucky_gold_mouse.svg',
        'file_url'       => 'uploads/gifts/lucky_gold_mouse.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'BAG ITEM',
        'description'    => 'Backpack inventory lucky golden tortoise for good health.',
        'sort_order'     => 52,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Free Gift Voucher Ticket',
        'coins'          => 100,
        'coin_price'     => 100,
        'category'       => 'bag',
        'image'          => 'uploads/gifts/love_mailbox.svg',
        'icon_url'       => 'uploads/gifts/love_mailbox.svg',
        'animation_url'  => 'uploads/gifts/love_mailbox.svg',
        'file_url'       => 'uploads/gifts/love_mailbox.svg',
        'animation_type' => 'shine_burst',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'TICKET',
        'description'    => 'Free live gift coupon ticket stored in user backpack.',
        'sort_order'     => 53,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'VIP Avatar Frame Box',
        'coins'          => 999,
        'coin_price'     => 999,
        'category'       => 'bag',
        'image'          => 'uploads/gifts/royal_crown_gift.svg',
        'icon_url'       => 'uploads/gifts/royal_crown_gift.svg',
        'animation_url'  => 'uploads/gifts/royal_crown_gift.svg',
        'file_url'       => 'uploads/gifts/royal_crown_gift.svg',
        'animation_type' => 'sparkle_tiara',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'FRAME',
        'description'    => 'Backpack collectible profile avatar frame reward.',
        'sort_order'     => 54,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],

    // ==========================================
    // ⭐ 8. POPULAR GIFTS (High Frequency / Entry)
    // ==========================================
    [
        'name'           => 'Rose Bouquet',
        'coins'          => 99,
        'coin_price'     => 99,
        'category'       => 'popular',
        'image'          => 'uploads/gifts/rose_bouquet_gift.svg',
        'icon_url'       => 'uploads/gifts/rose_bouquet_gift.svg',
        'animation_url'  => 'uploads/gifts/rose_bouquet_gift.svg',
        'file_url'       => 'uploads/gifts/rose_bouquet_gift.svg',
        'animation_type' => 'flying_petals',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'POPULAR',
        'description'    => 'Single red rose bouquet with floating sparkle petals.',
        'sort_order'     => 55,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Teddy Bear Love',
        'coins'          => 999,
        'coin_price'     => 999,
        'category'       => 'popular',
        'image'          => 'uploads/gifts/teddy_bear_gift.svg',
        'icon_url'       => 'uploads/gifts/teddy_bear_gift.svg',
        'animation_url'  => 'uploads/gifts/teddy_bear_gift.svg',
        'file_url'       => 'uploads/gifts/teddy_bear_gift.svg',
        'animation_type' => 'bounce_3d',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'CUTE',
        'description'    => 'Cuddly animated teddy bear holding a glowing heart.',
        'sort_order'     => 56,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Birthday Cake',
        'coins'          => 1314,
        'coin_price'     => 1314,
        'category'       => 'popular',
        'image'          => 'uploads/gifts/birthday_cake.svg',
        'icon_url'       => 'uploads/gifts/birthday_cake.svg',
        'animation_url'  => 'uploads/gifts/birthday_cake.svg',
        'file_url'       => 'uploads/gifts/birthday_cake.svg',
        'animation_type' => 'confetti_cake',
        'format'         => 'svg',
        'display_type'   => 'overlay',
        'badge'          => 'CELEBRATION',
        'description'    => '3-tier luxury candle celebration cake with confetti shower.',
        'sort_order'     => 57,
        'is_active'      => true,
        'is_broadcast'   => false,
    ],
    [
        'name'           => 'Champagne Pop',
        'coins'          => 1999,
        'coin_price'     => 1999,
        'category'       => 'popular',
        'image'          => 'uploads/gifts/champagne_gift.svg',
        'icon_url'       => 'uploads/gifts/champagne_gift.svg',
        'animation_url'  => 'uploads/gifts/champagne_gift.svg',
        'file_url'       => 'uploads/gifts/champagne_gift.svg',
        'animation_type' => 'fullscreen_champagne',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'CHEERS',
        'description'    => 'Sparkling golden champagne bottle pop with bubbles.',
        'sort_order'     => 58,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // 💎 9. LUXURY GIFTS (Supercars, Jets & Yachts)
    // ==========================================
    [
        'name'           => 'Sports Bike Ninja',
        'coins'          => 3333,
        'coin_price'     => 3333,
        'category'       => 'luxury',
        'image'          => 'uploads/gifts/sports_bike_gift.svg',
        'icon_url'       => 'uploads/gifts/sports_bike_gift.svg',
        'animation_url'  => 'uploads/gifts/sports_bike_gift.svg',
        'file_url'       => 'uploads/gifts/sports_bike_gift.svg',
        'animation_type' => 'speed_drive',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'SPEED',
        'description'    => 'Supercharged sports bike zooming across the live room.',
        'sort_order'     => 59,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Luxury Supercar',
        'coins'          => 5550,
        'coin_price'     => 5550,
        'category'       => 'luxury',
        'image'          => 'uploads/gifts/sports_car_gift.svg',
        'icon_url'       => 'uploads/gifts/sports_car_gift.svg',
        'animation_url'  => 'uploads/gifts/sports_car_gift.svg',
        'file_url'       => 'uploads/gifts/sports_car_gift.svg',
        'animation_type' => 'drive_in_drift',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'SUPERCAR',
        'description'    => 'Sleek golden supercar sliding into the live stream.',
        'sort_order'     => 60,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'VIP Helicopter',
        'coins'          => 15000,
        'coin_price'     => 15000,
        'category'       => 'luxury',
        'image'          => 'uploads/gifts/helicopter_gift.svg',
        'icon_url'       => 'uploads/gifts/helicopter_gift.svg',
        'animation_url'  => 'uploads/gifts/helicopter_gift.svg',
        'file_url'       => 'uploads/gifts/helicopter_gift.svg',
        'animation_type' => 'flying_helicopter',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'VIP ARRIVAL',
        'description'    => 'Golden VIP helicopter landing with spotlight illumination.',
        'sort_order'     => 61,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Supersonic Private Jet',
        'coins'          => 25000,
        'coin_price'     => 25000,
        'category'       => 'luxury',
        'image'          => 'uploads/gifts/private_jet_gift.svg',
        'icon_url'       => 'uploads/gifts/private_jet_gift.svg',
        'animation_url'  => 'uploads/gifts/private_jet_gift.svg',
        'file_url'       => 'uploads/gifts/private_jet_gift.svg',
        'animation_type' => 'flying_jet_trail',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'PRIVATE JET',
        'description'    => 'Luxury supersonic private jet flying across the screen.',
        'sort_order'     => 62,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Mega Luxury Yacht',
        'coins'          => 50000,
        'coin_price'     => 50000,
        'category'       => 'luxury',
        'image'          => 'uploads/gifts/luxury_yacht_gift.svg',
        'icon_url'       => 'uploads/gifts/luxury_yacht_gift.svg',
        'animation_url'  => 'uploads/gifts/luxury_yacht_gift.svg',
        'file_url'       => 'uploads/gifts/luxury_yacht_gift.svg',
        'animation_type' => 'ocean_cruise',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '50K YACHT',
        'description'    => 'Triple-deck ocean cruiser yacht sailing over luminous waves.',
        'sort_order'     => 63,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // ⚡ 10. EFFECTS / 3D GIFTS (Dragons, Battleships & Magic)
    // ==========================================
    [
        'name'           => 'Flaming Fire Dragon',
        'coins'          => 20000,
        'coin_price'     => 20000,
        'category'       => 'effects',
        'image'          => 'uploads/gifts/dragon_gift.svg',
        'icon_url'       => 'uploads/gifts/dragon_gift.svg',
        'animation_url'  => 'uploads/gifts/dragon_gift.svg',
        'file_url'       => 'uploads/gifts/dragon_gift.svg',
        'animation_type' => 'dragon_roar_fire',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'DRAGON 3D',
        'description'    => 'Mythic oriental dragon soaring breathing golden flames.',
        'sort_order'     => 64,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Flying Phoenix Rebirth',
        'coins'          => 30000,
        'coin_price'     => 30000,
        'category'       => 'effects',
        'image'          => 'uploads/gifts/phoenix_gift.svg',
        'icon_url'       => 'uploads/gifts/phoenix_gift.svg',
        'animation_url'  => 'uploads/gifts/phoenix_gift.svg',
        'file_url'       => 'uploads/gifts/phoenix_gift.svg',
        'animation_type' => 'phoenix_flight',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'PHOENIX 3D',
        'description'    => 'Immortal fire phoenix spreading radiant wings.',
        'sort_order'     => 65,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Interstellar Battleship',
        'coins'          => 75000,
        'coin_price'     => 75000,
        'category'       => 'effects',
        'image'          => 'uploads/gifts/space_battleship.svg',
        'icon_url'       => 'uploads/gifts/space_battleship.svg',
        'animation_url'  => 'uploads/gifts/space_battleship.svg',
        'file_url'       => 'uploads/gifts/space_battleship.svg',
        'animation_type' => 'battleship_laser',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => '75K WARP',
        'description'    => 'Massive cosmic dreadnought starship firing laser beams.',
        'sort_order'     => 66,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Magic Genie Lamp',
        'coins'          => 15000,
        'coin_price'     => 15000,
        'category'       => 'effects',
        'image'          => 'uploads/gifts/genie_lamp.svg',
        'icon_url'       => 'uploads/gifts/genie_lamp.svg',
        'animation_url'  => 'uploads/gifts/genie_lamp.svg',
        'file_url'       => 'uploads/gifts/genie_lamp.svg',
        'animation_type' => 'mystic_smoke',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'WISH 3D',
        'description'    => 'Mystical gold genie lamp granting opulent wishes.',
        'sort_order'     => 67,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],

    // ==========================================
    // 🌟 11. VIP EXCLUSIVE GIFTS
    // ==========================================
    [
        'name'           => 'Royal Sovereign Crown',
        'coins'          => 17700,
        'coin_price'     => 17700,
        'category'       => 'vip',
        'image'          => 'uploads/gifts/royal_crown_gift.svg',
        'icon_url'       => 'uploads/gifts/royal_crown_gift.svg',
        'animation_url'  => 'uploads/gifts/royal_crown_gift.svg',
        'file_url'       => 'uploads/gifts/royal_crown_gift.svg',
        'animation_type' => 'crown_descend_gold',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'ROYAL VIP',
        'description'    => 'Imperial 24K gold crown crowning the host.',
        'sort_order'     => 68,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
    [
        'name'           => 'Mythic Treasure Chest',
        'coins'          => 35000,
        'coin_price'     => 35000,
        'category'       => 'vip',
        'image'          => 'uploads/gifts/treasure_chest.svg',
        'icon_url'       => 'uploads/gifts/treasure_chest.svg',
        'animation_url'  => 'uploads/gifts/treasure_chest.svg',
        'file_url'       => 'uploads/gifts/treasure_chest.svg',
        'animation_type' => 'chest_burst_gems',
        'format'         => 'svg',
        'display_type'   => 'fullscreen',
        'badge'          => 'JACKPOT',
        'description'    => 'Ancient treasure chest bursting with diamonds.',
        'sort_order'     => 69,
        'is_active'      => true,
        'is_broadcast'   => true,
    ],
];

echo "Seeding " . count($allGifts) . " gifts into database...\n";

foreach ($allGifts as $giftData) {
    Gift::updateOrCreate(
        ['name' => $giftData['name']],
        $giftData
    );
}

echo "Successfully seeded " . Gift::count() . " gifts in database!\n";
